apiVersion: skaffold/v3
kind: Config
metadata:
  name: hello-gin2

deploy:
  kubectl: {}

manifests:
  rawYaml:
     - deployment.yaml

build:
  artifacts:
  - image: hello-gin

  # Comment following lines below to build locally
  cluster:
    dockerConfig:
      secretName: kaniko
